### ISSUE TITLE
file_exists error in xchem/init.lua

### ISSUE THREAD

**Issue by localalex** [JavaFXpert/QiskitBlocks#14]
Please use use local implementation of file_exists. It was removed from API. Same as here https://github.com/RacsoRhodes/travelpoints/issues/8

**Comment by HuangJunye** [comment]
@localalex Thanks for finding the source of this error. I have been struggling to get it working. Perhaps I need to install Minetest 5.1.0 for the time being.

**Comment by HuangJunye** [comment]
Links for Minetest 5.1.0. For Mac, you can download the installer here: https://github.com/krondor-game/minetest/releases?after=2019-07-23. For Windows, download here: https://forum.minetest.net/viewtopic.php?t=23484​​​​​​​

**Comment by HuangJunye** [comment]
Fixed by PR #15 Tested working on Mac with Minetest 5.2.0 Closing the issue.

**Comment by JavaFXpert** [comment]
Thanks Alexander!
