### ISSUE TITLE
Crash on entering world in minetest 5.3 due to changed collision handling

### ISSUE THREAD

**Issue by the-legend-of-lia** [JavaFXpert/QiskitBlocks#17]
![image](https://user-images.githubusercontent.com/16793587/94306855-901fcf80-ff28-11ea-940c-85f661914893.png)

**Steps to reproduce the bug:**
Enter world of QiskitBlocks while running minetest 5.3 - confirmed by two people the bug can be reproduced on both minetest's installer download and on installing minetest from source.  Sometimes crashes a few seconds after entering, usually crashes immediately.  The bug report message is screenshotted above.

**Findings from investigating the cause:**
QiskitBlocks is compatible with minetest 5.1 and 5.2.
From minetest 5.2 to 5.3, the on_step function now has an extra argument, moveresult which is a table with collision info that's only available if physical=true.
Looking at minetest's 5.2 -> 5.3 changelog, this pull request is the only one having to do with collision:
[](https://github.com/minetest/minetest/pull/9343) 

The collision table looks like:
```
{
    touching_ground = boolean,
    collides = boolean,
    standing_on_object = boolean,
    collisions = {
        {
            type = string, -- "node" or "object",
            axis = string, -- "x", "y" or "z"
            node_pos = vector, -- if type is "node"
            old_speed = vector,
            new_speed = vector,
        },
        ...
    }
}
```

Thank you!

**Comment by JavaFXpert** [comment]
Thanks for raising this issue, Lia! I've address it, so please try Minetest 5.3 again and browse/install QiskitBlocks from the Content tab as usual.

**Comment by JavaFXpert** [comment]
Updated item_entity.lua
