### ISSUE TITLE
Server error?

### ISSUE THREAD

**Issue by quantumAnsatz** [JavaFXpert/QiskitBlocks#21]
Hello I am running Minetest on Mac Catalina, and everytime I point and click on a circuit in the game, but the game keeps crashing with the following error:

```
AsyncErr: ServerThread::run Lua: Runtime error from mod 'q_command' in callback item_OnPlace(): Runtime error from mod 'q_command' in callback node_on_punch(): ...port/minetest/games/qiskitblocks/mods/q_command/init.lua:2100: attempt to index global 'request_http_api' (a nil value)
stack traceback:
	...port/minetest/games/qiskitblocks/mods/q_command/init.lua:2100: in function <...port/minetest/games/qiskitblocks/mods/q_command/init.lua:1235>
	[C]: in function 'punch_node'
	...ames/qiskitblocks/mods/circuit_blocks/circuit_blocks.lua:1626: in function 'on_rightclick'
	.../d/minetest.app/Contents/Resources/builtin/game/item.lua:426: in function <.../d/minetest.app/Contents/Resources/builtin/game/item.lua:419>
stack traceback:
	[C]: in function 'punch_node'
	...ames/qiskitblocks/mods/circuit_blocks/circuit_blocks.lua:1626: in function 'on_rightclick'
	.../d/minetest.app/Contents/Resources/builtin/game/item.lua:426: in function <.../d/minetest.app/Contents/Resources/builtin/game/item.lua:419>
```

**Comment by maugomezv** [comment]
@JavaFXpert

**Comment by quantumAnsatz** [comment]
I was getting the following error in the console at the beginning of the game
`ERROR[Main]: Secure setting secure.http_mods isn’t allowed, so was ignored.`

So I went to Minetest settings -> All settings -> Server/Singleplayer -> Security -> Trusted mods
And I added: 'q_command'

Now the game works but I do not know if something can be added to the game files to make this work more naturally.

**Comment by JavaFXpert** [comment]
Nice work!

**Comment by Hiradur** [comment]
I got the impression that QiskitBlocks is not allowed to change the security setting necessary for QiskitBlocks on its own. Hence it seems to be necessary to add `q_command` to the list of `secure.http_mods` by adding it to the `minetest.conf` file of the engine (not the `minetest.conf` file of the QiskitBlocks game). `q_command` then also appears in the list of `HTTP-mods` in the GUI. The list of trusted mods is still empty in my case, so adding it to this list might not be necessary.

Perhaps this should be explained in a readme or something.

**Comment by JavaFXpert** [comment]
Very good point. Would you mind doing a PR on the README.md ?

Regards,
Jim

**Comment by Hiradur** [comment]
I'm on it.
